apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-semver
  description: Semver library for the Maven ecosystem
  tags:
    - maven
  annotations:
    github.com/project-slug: snyk/maven-semver
    github.com/team-slug: snyk/os-managed
spec:
  type: external-library
  lifecycle: "-"
  owner: os-managed
